print("This is my first Git project")
name = input("Enter your first name: ")
print("Welcome,", name)
age = input("Enter your age: ")
print(f"Hello {name}! Your are {age} years old.")
print("Git is easy to understand once you get the hang of it \n you can do it")
